### ISSUE TITLE
unversioned files mess around in the middle

### ISSUE THREAD

**Issue by npf** [oar-team/oar-docker#20]
I have a sources/visualization_interfaces/DrawGantt-SVG/drawgantt.php in the source aside with the versioned sources/visualization_interfaces/DrawGantt-SVG/drawgantt.php.in.

When doing oardocker install, the /usr/local/share/oar-web-status/drawgantt-svg/drawgantt.php.in seems to be the unversioned drawgantt.php mentioned above instead of the one that should be generated from drawgantt.php.in

**Comment by SalemHarrache** [comment]
What about doing a “git clean -Xfd” before the installation?

It should not delete the unversioned files in the host machine directory (use of copy-on-write).
