### ISSUE TITLE
need a command to restart containers after a reboot

### ISSUE THREAD

**Issue by npf** [oar-team/oar-docker#21]
I need a command to restart containers after a reboot, without loosing the changes done since the initial oardocker start. 
oardocker start currently reset the environment to a previous container snapshot, hence it does suit the need.

Maybe also add a stop command that actually just stop the containers, but do not drop them.

**Comment by SalemHarrache** [comment]
I made the workflow easier on purpose, to restrict the number of commands.

On the new version (0.4.0), I put back the command ``oardocker reset`` that is used to relaunch containers.

You can also do it manually with docker. All you have to do is get the container ID (with ``oardocker status``) and execute:

```
docker stop|kill <container_id>
docker start <container_id>
```
