### ISSUE TITLE
remove deps to ruby

### ISSUE THREAD

**Issue by SalemHarrache** [oar-team/oar-docker#24]
Installing chandler dependancy takes too long and sometimes freezes.

```
frontend |  -> 023b475d6c51
frontend | Removing intermediate container 1aa8682b0fa3
frontend | Step 9 : RUN gem install rest-client naturalsort rspec
frontend |  -> Running in dc753488dcd5
```
I think it may be appropriate to drop it to reduce build time.

I suggest rewriting chandler in python to resolve this issue :)

**Comment by bzizou** [comment]
I can do that :-)

**Comment by npf** [comment]
The bug should be: "remove deps to ruby" then.

**Comment by SalemHarrache** [comment]
I suggest using  requests (http://docs.python-requests.org/en/latest/)

**Comment by SalemHarrache** [comment]
Python version of chandler is here : https://github.com/oar-team/chandler
