### ISSUE TITLE
build failure - max() arg is an empty sequence

### ISSUE THREAD

**Issue by EudesRobin** [oar-team/oar-docker#26]
eudes@laptop:~/test$ sudo oardocker build
Starting oardocker build

Error: max() arg is an empty sequence

I don't modify any files after oardocker init. I already setup oar-docker without any troubles, maybe it's related to the last updates (?) ; I recently upgrade oar-docker to the lastet version.

An other oar-docker environment is setup in a other directory ( previously build with an old oar-docker version, I can use it currently ), but I don't think it's related. Each environment is isolated, right ?

**Comment by npf** [comment]
Hi Eudes, why run oardocker as sudo ? root privileges should not be required as long as your user belongs to the docker group (at least on Debian).

**Comment by EudesRobin** [comment]
Hi,
it's just a default setting, (https://docs.docker.com/installation/ubuntulinux/#giving-non-root-access), but you are right, it's better to create a docker group. After creating the docker group and add the current user, I can now use oardocker without sudo, but the error remains.

**Comment by SalemHarrache** [comment]
I released oar-docker 0.4.3 with --debug option. Could you try and
give us the traceback?

``oardocker --debug build``

I also need to check your .oardocker env directory. Could you send me
an archive copy ?


Thank you

**Comment by EudesRobin** [comment]
The release 0.4.3 fix it, something went wrong during th init command, now it's okay :+1: 

"
Fixed oardocker init subcommand (#22)) "

Thanks for the update ;)
