### ISSUE TITLE
improvement for the dev environement

### ISSUE THREAD

**Issue by npf** [oar-team/oar-docker#34]
set OAREXEC_DEBUG_MODE="1" in oar.conf

make /etc/oar/job_resource_manager_cgroup.pl a symlink to the installed location (instead of a copy)

**Comment by SalemHarrache** [comment]
Hi @npf ,

About OAREXEC_DEBUG_MODE="1", it's done.

However, for the file `/etc/oar/job_resource_manager_cgroup.pl`, it's impossible as things now stand. 

Indeed, we can't keep OAR sources at the end of a `oardocker install`.
And I'm guessing, what you actually want is a symbolic link to your sources on your HOST machine...

Anyway, one solution is to do a mount bind of this file directly, it's cleaner.

```
$ oardocker start -v $PWD:/src/oar -v $PWD/sources/core/tools/job_resource_manager_cgroups.pl:/etc/oar/job_resource_manager_cgroup.pl
```

See you!

**Comment by SalemHarrache** [comment]
Done ! :)
