### ISSUE TITLE
use apache config from sources instead of rewriting it.

### ISSUE THREAD

**Issue by npf** [oar-team/oar-docker#35]
currently the apache config file for the api is written in
./images/frontend/install_oar.sh

it would be better to use and modify if needed the one from the sources.

**Comment by SalemHarrache** [comment]
that's what we're [already currently doing](https://github.com/oar-team/oar-docker/blob/21c3c470faa88f00005522d4d12256d3363ee1c9/oardocker/templates/jessie/images/frontend/install_oar.sh#L71)
