### ISSUE TITLE
set cosystem and deploy frontend to "frontend" and add option to install oar-node on the frontend

### ISSUE THREAD

**Issue by npf** [oar-team/oar-docker#36]
in oar.conf: set cosystem and deploy frontend to "frontend" 

then in order for cosystem/deploy jobs to work, the frontend must also have oar-node installed (sshd running on 6667).

this could be the default, or just an option for oardocker install...

**Comment by SalemHarrache** [comment]
What about creating a new env for this ? like jessie-cosystem ?

**Comment by npf** [comment]
I think it's a bit overkill, bettter do it as the default.
