### ISSUE TITLE
resources are no more intialized since oar_resources_init was modified

### ISSUE THREAD

**Issue by bzizou** [oar-team/oar-docker#37]
The script setup_some_resources.sh still uses /tmp/oar_resources_init.cmd for nodes creation, but it should now use  /tmp/oar_resources_init.XXXX with XXXX a random string given by oar_resources_init
As a consequence, there's no more nodes in the oardocker cluster.

**Comment by npf** [comment]
The script now provides more options: the oarproperty and arnodesetting commands can be executed directly, without the need to sources a script file afterward. 

See `oar_resources_init -h'
