### ISSUE TITLE
oardocker install crashes with ln: failed to create symbolic link `/etc/apache2/conf-enabled/oar-restful-api.conf': No such file or directory

### ISSUE THREAD

**Issue by lnussbaum** [oar-team/oar-docker#39]

**Comment by lnussbaum** [comment]
works with jessie, fails with wheezy

**Comment by npf** [comment]
@SalemHarrache : Jessie should be the default.
Wheezy can be deprecated, we do not have the task force to support both.

**Comment by augu5te** [comment]
Jessie is already the default. I changed the Readme.
