### ISSUE TITLE
oardocker logs performance issue

### ISSUE THREAD

**Issue by npf** [oar-team/oar-docker#40]
with 100 nodes (400 resources), running
$ oardocker logs -f 
eats all my cpu.

To have less lines to display, I added -t 1
$ oardocker logs -t 1 -f 
-> less lines to display in a first time, but cpu is burning anyway...

**Comment by npf** [comment]
FYI: I see the following message
tail: inotify cannot be used, reverting to polling: Too many open files

**Comment by mickours** [comment]
The too many open file issue can be treat by raising up the number of open file descriptor limit of the user running the docker daemon.
Depending on your init system you should modify the launching service script/config. Here is my systemd service file as an example:
```
[Unit]
Description=Docker Application Container Engine
Documentation=https://docs.docker.com
After=network.target docker.socket
Requires=docker.socket

[Service]
Type=notify
ExecStart=/usr/bin/docker daemon -H fd://
MountFlags=slave
LimitNOFILE=1048576
LimitNPROC=1048576
LimitCORE=infinity

[Install]
WantedBy=multi-user.target
```

**Comment by mickours** [comment]
Here is an example for Debian 8:
https://sskaje.me/systemd-ulimit/
