### ISSUE TITLE
oardocker usage -> default wheezy is out of date and invalid

### ISSUE THREAD

**Issue by npf** [oar-team/oar-docker#41]
neyron@takelma:~/scm/OAR/oar (2.5 $%=)$ oardocker init --help
Usage: oardocker init [OPTIONS]

  Initialize a new environment.

Options:
  -f, --force                     Overwrite existing env
  -e, --env [jessie-cigri|jessie]
                                  Use variant X of the Dockerfiles [default:
                                  wheezy]
  -h, --help                      Show this message and exit.

**Comment by SalemHarrache** [comment]
Fixed since oardocker  (~) v1.0.0
```
Usage: oardocker init [OPTIONS]

  Initialize a new environment.

Options:
  -f, --force               Overwrite existing env
  -e, --env [jessie|coorm]  Use variant X of the Dockerfiles  [default: jessie]
  -h, --help                Show this message and exit.
```
