### ISSUE TITLE
Do we have a documentation for the base image update?

### ISSUE THREAD

**Issue by npf** [oar-team/oar-docker#42]
Or could it be a oar-docker command ?

**Comment by SalemHarrache** [comment]
Base image reproducibility is ensured by the fact that the kameleon recipe is provided in oar-docker sources.

*oar-docker* project aims to start the development quickly without losing too much time configuring things. That is why I didn't add the base image creation process in the prerequisites to use it, it has little to do with OAR.

I host the image on the docker hub website, but there is always the possibility to generate it yourself. It is not clearly stipulated, but I consider that when you are looking for the origins of the base image, you must check by yourself the sources.

I'll add a section in the README to redirect the curious people ;-)
