### ISSUE TITLE
oardocker exec does not work with complex commands

### ISSUE THREAD

**Issue by npf** [oar-team/oar-docker#50]
Examples:
```
$ oardocker exec frontend "cd /tmp ; pwd"
/home/docker

$ oardocker exec frontend bash -c "cd /tmp ; pwd"
/home/docker

$ oardocker exec frontend 'bash -c "cd /tmp ; pwd"'
/home/docker
```

trying with `docker exec` (need some tricks to get the docker image name + set user...):
```
$ image=$(docker ps | grep frontend | cut -f1 -d\  ) && \
> docker exec -ti -u docker $image bash -c 'cd /tmp; pwd'
/tmp
```

**Comment by npf** [comment]
Hello @SalemHarrache,
Your commit does not seem to improve the situation for now ?
Also I am looking at the file: https://github.com/oar-team/oar-docker/blob/master/oardocker/templates/common/images/base/bin/exec_in_container
```
#!/bin/bash
WORKDIR=$1
CMD="${@:2}"

cd $WORKDIR && eval "$CMD"
```
-> not sure to understand: should the `eval` be replaced with `exec`
-> why this need to `cd $WORKDIR` before ?

**Comment by npf** [comment]
Ok got it for the eval. Still not working for my though.

**Comment by npf** [comment]
Woops: works ok when doing things right :-)

**Comment by npf** [comment]
Thanks @SalemHarrache !

**Comment by npf** [comment]
New error:
```
$ oardocker connect
/usr/local/bin/exec_in_container: line 5: cat /etc/motd && bash: No such file or directory
```
`$ oardocker exec frontend "cat /etc/motd && bash"` works ok.

**Comment by SalemHarrache** [comment]
Hi npf :)

For your first use case, this command should be enough:
```
$ oardocker exec -w /tmp frontend "pwd"
/tmp
```

We use a wrapper to execute commands inside containers and it's true that the escaping is a bit weird resulting in the two commands not launching in the same shell process. I've fixed the problem now, I'll commit the solution right now ;)

So now this command should send back the following result:

```
$ oardocker exec -l root -w /home frontend 'pwd; cd /tmp; pwd'
/home
/tmp
```

Thank you and see you next time!

**Comment by npf** [comment]
Great, thanks ! Closing.
